[package]
name = "template"
version = "1.0.0"
authors = ["The Teaclave Authors"]

[lib]
name = "sample" # Library name. If you change this, please reflect those changes in the Makefile on the variable ENCLAVE_CARGO_LIB
crate-type = ["staticlib"] 

[features]
default = []

[target.'cfg(not(target_env = "sgx"))'.dependencies] # You can remove what you don't need, except types and tstd
sgx_types = { path = "/root/dev/incubator-teaclave-sgx-sdk/sgx_types" }
sgx_tstd = { path = "/root/dev/incubator-teaclave-sgx-sdk/sgx_tstd", features = ["backtrace"] }
sgx_tcrypto = { path = "/root/dev/incubator-teaclave-sgx-sdk/sgx_tcrypto" }
sgx_trts = { path = "/root/dev/incubator-teaclave-sgx-sdk/sgx_trts" }
sgx_tseal = { path = "/root/dev/incubator-teaclave-sgx-sdk/sgx_tseal" }
sgx_serialize = { path = "/root/dev/incubator-teaclave-sgx-sdk/sgx_serialize" }
sgx_alloc = { path = "/root/dev/incubator-teaclave-sgx-sdk/sgx_alloc" }
sgx_libc = { path = "/root/dev/incubator-teaclave-sgx-sdk/sgx_libc" }

[dependencies]

[patch.'https://github.com/apache/teaclave-sgx-sdk.git']